title: My personal Blog
author: Toni Mayans
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog test for github pages.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
